apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  ports:
    - port: 8080
  selector:
    name: api-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: api-gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      app: api-gateway-deployment
      namespace: api-gateway        
    spec:
      containers:
      - name: api-gateway
        image: gcr.io/tugas-akhir-hana/github-hanalaydrus-api-gateway:86f109479ef62972d84e437b10b86bf926afe82d
        
      restartPolicy: Always