# Service setup
apiVersion: v1
kind: Service
metadata:
  name: traffic-streaming-service
  labels:
    group: traffic-streaming
    tier: service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    group: traffic-streaming
    tier: service
  type: LoadBalancer
  loadBalancerIP: "35.187.247.127"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traffic-streaming-service
  labels:
    group: traffic-streaming
    tier: service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        group: traffic-streaming
        tier: service
    spec:
      containers:
      - name: traffic-streaming-service
        image: gcr.io/tugas-akhir-hana/github-hanalaydrus-traffic-streaming:latest
        ports:
        - name: http-strmg-cam
          containerPort: 5000

      restartPolicy: Always